services:

  lunch:
    image: "web:gh"
    build: .
    environment:
      - TITLE=${TITLE:-Lunchtime [dev]}
      - COLOR=${COLOR:-yellow}
    ports:
      - 80
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080

volumes:
  vipdb:

networks:
  default:
    name: traefik
    external: true