services:
  proxy:
    image: nginxproxy/nginx-proxy:1.6
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lunch:
    image: "web:gh"
    build: .
    environment:
      - TITLE=${TITLE:-Lunchtime [dev]}
      - COLOR=${COLOR:-yellow}
      - VIRTUAL_HOST=lunch.lvh.me
    ports:
      - 80
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=db.lvh.me
    ports:
      - 8080

volumes:
  vipdb: