services:
  # proxy:
  #   image: nginxproxy/nginx-proxy:1.6
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

  traefik:
    image: traefik:1.7-alpine
    command:
      - --debug
      - --retry
      - --rest
      - --docker.domain=${DOMAIN:-lvh.me}
      - --docker.network=dev_default
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  lunch:
    image: "web:gh"
    build: .
    environment:
      - TITLE=${TITLE:-Lunchtime [dev]}
      - COLOR=${COLOR:-yellow}
    ports:
      - 80
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080

volumes:
  vipdb: